### ISSUE TITLE
Compatibility with Beets 2.5.0

### ISSUE THREAD

**Issue by Neurrone** [adammillerio/beets-copyartifacts#15]
I get the following error on import

```
** error loading plugin copyartifacts
Traceback (most recent call last):
  File "/lsiopy/lib/python3.12/site-packages/beets/plugins.py", line 428, in _get_plugin
    namespace = import_module(f"{PLUGIN_NAMESPACE}.{name}")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/lsiopy/lib/python3.12/site-packages/beetsplug/copyartifacts.py", line 10, in <module>
    from beets.library import DefaultTemplateFunctions
ImportError: cannot import name 'DefaultTemplateFunctions' from 'beets.library' (/lsiopy/lib/python3.12/site-packages/beets/library/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lsiopy/lib/python3.12/site-packages/beets/plugins.py", line 430, in _get_plugin
    raise PluginImportError(name) from exc
beets.plugins.PluginImportError: Could not import plugin copyartifacts
```

**Comment by adammillerio** [comment]
Thanks for the PR! I have merged it and published v0.1.6 to pypi.

**Comment by doronbehar** [comment]
I'm still experiencing test failures with version 0.1.6 and `beets` version 2.5.1:

```
pytest flags: -m pytest -rfEs
============================= test session starts ==============================
platform linux -- Python 3.13.11, pytest-8.4.2, pluggy-1.6.0
rootdir: /build/source
plugins: anyio-4.12.0
collected 0 items / 5 errors                                                   

==================================== ERRORS ====================================
___________________ ERROR collecting tests/test_filename.py ____________________
tests/test_filename.py:4: in <module>
    from tests.helper import CopyArtifactsTestCase
tests/helper.py:260: in <module>
    class TestImportSession(importer.ImportSession):
tests/helper.py:280: in TestImportSession
    default_choice = importer.action.APPLY
                     ^^^^^^^^^^^^^^^
E   AttributeError: module 'beets.importer' has no attribute 'action'. Did you mean: 'Action'?
_________________ ERROR collecting tests/test_flatdirectory.py _________________
tests/test_flatdirectory.py:4: in <module>
    from tests.helper import CopyArtifactsTestCase
tests/helper.py:260: in <module>
    class TestImportSession(importer.ImportSession):
tests/helper.py:280: in TestImportSession
    default_choice = importer.action.APPLY
                     ^^^^^^^^^^^^^^^
E   AttributeError: module 'beets.importer' has no attribute 'action'. Did you mean: 'Action'?
________________ ERROR collecting tests/test_nesteddirectory.py ________________
tests/test_nesteddirectory.py:4: in <module>
    from tests.helper import CopyArtifactsTestCase
tests/helper.py:260: in <module>
    class TestImportSession(importer.ImportSession):
tests/helper.py:280: in TestImportSession
    default_choice = importer.action.APPLY
                     ^^^^^^^^^^^^^^^
E   AttributeError: module 'beets.importer' has no attribute 'action'. Did you mean: 'Action'?
_________________ ERROR collecting tests/test_printignored.py __________________
tests/test_printignored.py:4: in <module>
    from tests.helper import CopyArtifactsTestCase, capture_log
tests/helper.py:260: in <module>
    class TestImportSession(importer.ImportSession):
tests/helper.py:280: in TestImportSession
    default_choice = importer.action.APPLY
                     ^^^^^^^^^^^^^^^
E   AttributeError: module 'beets.importer' has no attribute 'action'. Did you mean: 'Action'?
___________________ ERROR collecting tests/test_reimport.py ____________________
tests/test_reimport.py:5: in <module>
    from tests.helper import CopyArtifactsTestCase
tests/helper.py:260: in <module>
    class TestImportSession(importer.ImportSession):
tests/helper.py:280: in TestImportSession
    default_choice = importer.action.APPLY
                     ^^^^^^^^^^^^^^^
E   AttributeError: module 'beets.importer' has no attribute 'action'. Did you mean: 'Action'?
=============================== warnings summary ===============================
../../nix/store/9f0jp7f6f7gql5vi90hmnxvrf2wnqpgy-python3.13-confuse-2.0.1/lib/python3.13/site-packages/confuse/util.py:118
  /nix/store/9f0jp7f6f7gql5vi90hmnxvrf2wnqpgy-python3.13-confuse-2.0.1/lib/python3.13/site-packages/confuse/util.py:118: DeprecationWarning: 'pkgutil.get_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead
    loader = pkgutil.get_loader(name)

tests/helper.py:13
  /build/source/tests/helper.py:13: UserWarning: beets.mediafile is deprecated; use mediafile instead
    from beets import mediafile

beetsplug/__init__.py:1
  /build/source/beetsplug/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
    __import__('pkg_resources').declare_namespace(__name__)

../../nix/store/bq3172qx0c68yv0i4wy51y1bzln4wndr-python3.13-setuptools-80.9.0/lib/python3.13/site-packages/pkg_resources/__init__.py:3146
  /nix/store/bq3172qx0c68yv0i4wy51y1bzln4wndr-python3.13-setuptools-80.9.0/lib/python3.13/site-packages/pkg_resources/__init__.py:3146: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('beetsplug')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

beetsplug/__init__.py:1
  /build/source/beetsplug/__init__.py:1: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('beetsplug')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    __import__('pkg_resources').declare_namespace(__name__)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
ERROR tests/test_filename.py - AttributeError: module 'beets.importer' has no attribute 'action'. Did you ...
ERROR tests/test_flatdirectory.py - AttributeError: module 'beets.importer' has no attribute 'action'. Did you ...
ERROR tests/test_nesteddirectory.py - AttributeError: module 'beets.importer' has no attribute 'action'. Did you ...
ERROR tests/test_printignored.py - AttributeError: module 'beets.importer' has no attribute 'action'. Did you ...
ERROR tests/test_reimport.py - AttributeError: module 'beets.importer' has no attribute 'action'. Did you ...
!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!
======================== 5 warnings, 5 errors in 0.38s =========================
```

**Comment by lispcat** [comment]
> I'm still experiencing test failures with version 0.1.6 and `beets` version 2.5.1:

I too am experiencing these test failures. As a workaround I'm using the alternative plugin filetote, which worked for beets 2.5.1
